name: Development tests
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run only when a source file has been updated
  paths-filter:
    name: Check if should build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workflows:
              - 'app/**'
              - '*.kts'
  test:
    name: Tests without emulator
    runs-on: ubuntu-latest
    # Wait from the paths-filter to be completed before starting next-job
    needs: paths-filter
    if: github.event_name == 'release' || needs.paths-filter.outputs.output1 == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: Run lint and unit tests
        run: ./gradlew app:lintDebug app:testDebugUnitTest
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            app/build/outputs/lint*
            app/build/reports
